### ISSUE TITLE
Access policies can't be initialized for viewsets that don't subclass NamedModelViewset

### ISSUE THREAD

**Issue by fao89** [pulp/pulpcore#2077]
Author: @newswangerd (newswangerd)

Redmine Issue: 9671, https://pulp.plan.io/issues/9671

---

Pulpcore can only initialize access policies in the database for viewsets that are registered in the pulp/api/v3/ router (https://github.com/pulp/pulpcore/blob/main/pulpcore/app/apps.py#L219). Because of this, there is no easy way to initialize access policies in the database for apps that implement APIs outside of pulp/api/v3/ such as galaxy_ng, pulp_ansible and pulp_container.

**Comment by bmbouter** [comment]
I recommended we close this, but please comment if you think we should reopen. We're trying to keep open bugs/changes that we plan on working on, and I didn't think this was going to have a change made. Mostly it's because we have a workaround that seems good enough to use long-term.  The workaround is done by defining `urlpattern()` methods [like this](https://github.com/pulp/pulp_ansible/pull/798/files#diff-e11a4087ff75182a1c5c58b3812e77def3dccfe96c12e2f6261760225d5c41d2R175).
