### ISSUE TITLE
Protect (published) repository versions from deletion

### ISSUE THREAD

**Issue by zapp42** [pulp/pulpcore#2705]
Repositories may be automatically deleted if the retain-repo-versions setting is used. If a certain repository version is published (e.g. rpm publication + distribution), the published rpm repository will stop working. This is unexpected (at least to me).

Please add a setting to protect a repository version from being deleted (either automatically or manually). From my point of view, published repository version shall be protected automatically.

Discussion: 
https://discourse.pulpproject.org/t/should-publications-keep-certain-repository-versions-from-being-removed/448

**Comment by daviddavis** [comment]
> If a certain repository version is published (e.g. rpm publication + distribution), the published rpm repository will stop working.

I think of these repo versions as a ***distributed*** repo versions. Most users will probably want to cleanup/delete published repo versions (that aren't distributed) and their publications. Or at least that's what we'd want. I'd probably suggest the title of this issue be updated based on this distinction.

**Comment by daviddavis** [comment]
We really want to start using `retain_repo_versions` but this issue prevents us from doing so. I almost think this is maybe more of a bug than a feature.

First, the current behavior means that `retain_repo_versions` is unsafe and thus unusable. Even if you set it to a high number such as 100, it could still potentially delete a distributed repo version. A user could come along and add 101 packages into a repo one-by-one thus deleting the any distributed repo versions. Now ideally this wouldn't happen but we've had users do things like this.

The second thing I'd say is that this unexpected for most users. The discourse post seems to indicate this. 

A setting would work for us but I'd suggest fixing it for everyone since as I stated, I think `retain_repo_versions` is unusable. 

Also, our preference would be for `retain_repo_versions` to continue also cleanup publications so long as those publications aren't being distributed. Otherwise, we need some way to cleanup not-distributed publications in bulk.

**Comment by daviddavis** [comment]
We discussed this at [PulpCon](https://hackmd.io/@pulp/pulpcon_2023) and I'll try to summarize the consensus we reached:
- Having the automatic retain_repo_versions code clean up distributed repo versions (ie repo versions that are published and are being distributed by a distribution) is undesirable and unexpected.
- Solution is to add code to exclude distributed repo versions from consideration when cleaning up repo versions. Only repo versions that are not distributed are cleaned up.
- Number of repo verisons for a repo may exceed retain_repo_versions
- Possible future enhancements: add this check to when repo versions are manually deleted via the API (with a force delete flag?)
