### ISSUE TITLE
[EPIC] Unified API endpoint to determine if a file can be uploaded without error

### ISSUE THREAD

**Issue by ianballou** [pulp/pulpcore#2911]
**Is your feature request related to a problem? Please describe.**
In Katello, we need to create our own logic to avoid errors when uploading content to Pulp. With the recent issues around uploading Debian content, we realized it would be best to remove all of that logic from Katello and rely on Pulp as the source of truth.

**Describe the solution you'd like**
An API endpoint that Katello can reach with a name and/or sha256 checksum that will return if the content is uploadable or not. 

**Describe alternatives you've considered**
If not this, then Katello will need to continue holding separate rules for different content types.  Another potential solution could be to standardize the upload logic in Pulp plugins across all, but that sounds more difficult.

**Additional context**
The `find_duplicate_unit` method is an example of the logic Katello needs to implement to ensure file upload is a good user experience: https://github.com/Katello/katello/blob/master/app/services/katello/pulp3/pulp_content_unit.rb#L129

**Comment by quba42** [comment]
Just for completeness sake I wanted to mention another possible approach: Rather than Katello trying to anticipate if some given file can be uploaded as some given content type based on hard coded logic, Katello might just try to upload whatever the user wants to upload, and then handle possible exceptions returned by Pulp. Katello might still have to make assumptions about how to handle a given Pulp error for a given content type, but it would shift the logic for "does this already exist in Pulp?" back into Pulp.

**Comment by quba42** [comment]
I just had another thought for discussion: Might it make sense to have something like an `upload/` API endpoint for repositories (analogous to the existing `sync/` endpoint). That way, rather than expecting users to figure out whether some given file they want to add to a given repository already exists or not, users could simply use the "upload this file to this repository" endpoint, and it is then up to the Pulp plugin to decide what artifacts and content needs to be created, or if already existing artifacts/content can simply be used. This would place the onus for deduplication for uploads back onto plugin authors. I think this would be a much better user experience (and also satisfy the Katello requirement).

**Comment by ianballou** [comment]
> Might it make sense to have something like an `upload/` API endpoint for repositories (analogous to the existing `sync/` endpoint).

From a user perspective that would be even better. Since it would be so easy to use I wonder if it would be very difficult to implement :)

**Comment by mdellweg** [comment]
I maybe missing something, but the upload endpoint (POST on the content path) allows to specify a repository the content is supposed to be added.

**Comment by mdellweg** [comment]
> I'd be curious to see an example via the API

Damn, i fail to find any.

**Comment by mdellweg** [comment]
This is for sure related:
https://github.com/pulp/pulp-cli/issues/385

**Comment by quba42** [comment]
Looks like the demand for "make it easier to upload things _directly into pulp repositories_" is clear.
My clear preference (and the motivation for this ticket) would be for pulpcore to define some common interface for this, that all plugin authors need to implement. The alternative seems to be Katello, Pulp CLI, users using the API directly, all have to independently solve this problem for each plugin, and also need to maintain those implementations. => This does not sound appealing!

**Comment by quba42** [comment]
```
class SingleArtifactContentUploadSerializer(
    UploadSerializerFieldsMixin, SingleArtifactContentSerializer
):
    """
    A serializer for content_types with a single Artifact.

    The Artifact can either be specified via it's url or an uncommitted upload, or a new file can
    be uploaded in the POST data.
    Additionally a repository can be specified, to which the content unit will be added.

    When using this serializer, the creation of the real content must be wrapped in a task that
    touches the Artifact and locks the Upload and Repository when specified.
    """
```
If this were to be made to work as follows:
1.) Try to create a artifact from the uploaded file. If that artifact already exists, use the existing artifact.
2.) Try to create the content from the artifact from (1). If the content already exists, use the existing content.
3.) Add the content from (2) to the specified repo.

Then this provides the wanted workflow. I don't think this is currently the case. I believe the current behaviour is to throw errors if either the artifact or the content already exists, and then let the user pick up the pieces. So maybe this ticket could be reformulated to ask for "create or retrieve" functionality to be added to the `SingleArtifactContentUploadSerializer`?

**Comment by quba42** [comment]
If that is the case, then I guess the pulpcore part is done (and I need to open a pulp_deb issue like the pulp_file one above).

@mdellweg Do you know if there is some way to track which plugins do and do not implement this workflow? I guess that would be important information for Katello, so they can tell when to rework their upload code. Does that make sense @ianballou ?

**Comment by mdellweg** [comment]
I would maybe add a checkbox list here.

**Comment by MichalPysik** [comment]
I believe this is basically covered by https://github.com/pulp/pulpcore/pull/3083 since content can be re-used now
