### ISSUE TITLE
Remove `BaseDistribution` from the plugin API

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#2993]
We tried to do this once before but there were migration issues perhaps?

edit: See comment below
> Maybe we just update the docstring with info that it can't be removed until Pulp4. and use this issue for that .misc change.

**Comment by ipanova** [comment]
Posting some matrix convo that happened some time ago:

x9c4
Hey folks, do you think we are ready to remove the BaseDistribution model from the database? Or is there any reason not to do so?
^
dalley maybe you remember?
dralley
I don't remember the exact reason but I think it had to do with migrations.  Basically the historical migration record has lots of references to this BaseDistribution model
hopefully we wrote down the reason somewhere
x9c4
not in the code at least.
dralley
x9c4: https://pulp.plan.io/issues/8386#note-5
dralley
I think the TL;DR is:  the migrations happen all at once for a given app, be it pulpcore or a plugin, so if you do a speedrun through all the pulpcore migrations and remove the basedistribution model entirely, then the early migrations for some plugin will fail
in a new installation, where they haven't already been applied
x9c4
So we cannot reall remove it, because we do not controll all plugins migrations. I'l stop thinking about it again for a year.
x9c4
I was once looking into squashing migrations, but maybe for the same reasons of plugin interdependence we cannot really do this in Pulp.
dralley
Pulp 4 (tm)

**Comment by bmbouter** [comment]
We could at the least remove it from the plugin API and it would just live in the DB and the model definition inside of `pulpcore.app.models`.

**Comment by bmbouter** [comment]
Actually it already is removed from the plugin API https://github.com/pulp/pulpcore/blob/main/pulpcore/plugin/models/__init__.py Maybe we just update the docstring with info that it can't be removed until Pulp4. and use this issue for that .misc change.

**Comment by ipanova** [comment]
@bmbouter i agree

**Comment by mdellweg** [comment]
... until we squashed enough migrations we cannot remove it.
