### ISSUE TITLE
Odd/inconsistent naming for task list filters

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpcore#3357]
If you look at the params for [the task list endpoint](https://docs.pulpproject.org/pulpcore/restapi.html#tag/Tasks/operation/tasks_list), there's a `created_resources` filter that accepts a **single** uuid str and a `reserved_resources_record` which accepts an array of strings. I would expect them both to accept an array of strings I suppose but at the very least, it seems strange to me that the plural filter name accepts only a single uuid.

I suppose fixing the names would be backwards incompatible and would break people. Perhaps one solution is to update the `created_resources` to accept an array of uuids but also check and support a single uuid (for backwards compatibility).

**Comment by mdellweg** [comment]
The reserved_resources_record filter is not really useful in it's current state and considered deprecated. (We keep it around for backwards compatibility.)
We recently added filters that can properly search for shared and exclusive resources. https://github.com/pulp/pulpcore/pull/3282

The naming is odd, because the filters follow the actual field names. We may need to revisit that.

**Comment by daviddavis** [comment]
> We recently added filters that can properly search for shared and exclusive resources. https://github.com/pulp/pulpcore/pull/3282

This is great. I imagine this will ship in 3.22? Is there a date set yet for that?

**Comment by dkliban** [comment]
This is already addressed for 3.22.
