### ISSUE TITLE
[Task] Document that Pulp is incompatible with db-connection pools

### ISSUE THREAD

**Issue by mdellweg** [pulp/pulpcore#3505]
PgBouncer was identified to break Pulps expectations with advisory locks. We should document something to point people not reading their docs to ours.

Details: Pulp uses session based Postgres features, so connection pooling on the transaction level will fail. Since at least PgBouncer does not inspect the statements sent to the server for incompatible features, this will lead to bad issues including data corruption.

https://www.pgbouncer.org/features.html

**Comment by mdellweg** [comment]
We should document the minimal Postgres version needed to deploy Pulp, too.

**Comment by dralley** [comment]
>We should document the minimal Postgres version needed to deploy Pulp, too.

I think it works down to 10, but below 12 there are some additional spurious locking issues that newer versions don't seem to have.

**Comment by mdellweg** [comment]
That one may actually work.

> **It seems my pgpool-II does not do load balancing. Why?**
>
>    First of all, pgpool-II' load balancing is "session base", not "statement base". [...]

--
from: https://pgpool.net/mediawiki/index.php/FAQ

**Comment by ipanova** [comment]
Unless we want to commit to actually test this out, my suggestion would be to state in the docs what we know:
- that pulp is not compat with pgbouncer because that one supports only transaction pooling
- pulp is not compat with any db-connection pools that are transaction/statement based
- advise to check the docs for any db-connection pooling in question whether it is compat with session level pg advisory locks.
