### ISSUE TITLE
IPv6/IPv4 failover

### ISSUE THREAD

**Issue by gvde** [pulp/pulpcore#3862]
**Version**
Running katello-4.7.5-1.el8.noarch on AlmaLinux 8.7

**Describe the bug**
 I have noticed connections to almalinux repositories time out because the ipv6 address ports aren't responding.

repo.almalinux.org has two addresses:

```
# host repo.almalinux.org
repo.almalinux.org has address 67.222.0.50
repo.almalinux.org has IPv6 address 2600:4c00:400::2
```

The IPv4 address is fine:
```
# curl -v -4 https://repo.almalinux.org/
*   Trying 67.222.0.50...
* TCP_NODELAY set
* Connected to repo.almalinux.org (67.222.0.50) port 443 (#0)
* ALPN, offering h2
...
```

The IPv6 address is currently timing out:
```
# curl -v -6 https://repo.almalinux.org/
*   Trying 2600:4c00:400::2...
* TCP_NODELAY set
* connect to 2600:4c00:400::2 port 443 failed: Connection timed out
* Failed to connect to repo.almalinux.org port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to repo.almalinux.org port 443: Connection timed out
```

The repo syncs of all my almalinux repositories using repo.almalinux.org aren't working at the moment because the task fails after 5 minutes with
```
Request timed out for https://repo.almalinux.org/almalinux/8/BaseOS/x86_64/os/repodata/repomd.xml. Increasing the total_timeout value on the remote might help.
```

**To Reproduce**
Try to sync a repository from a host with IPv4 and IPv6 address where the IPv6 connection times out.

**Expected behavior**
The timeout should be much shorter and the sync should try the other IP addresses if one fails or times out and only fail if none of the IP addresses connect.

**Additional context**
https://community.theforeman.org/t/issues-with-repo-sync-from-repo-almalinux-org/33605

katello-4.7.5-1.el8.noarch
pulpcore-selinux-1.3.2-1.el8.x86_64
python39-pulp-ansible-0.15.0-1.el8.noarch
python39-pulp-certguard-1.5.5-1.el8.noarch
python39-pulp-cli-0.14.0-4.el8.noarch
python39-pulp-container-2.14.3-1.el8.noarch
python39-pulpcore-3.21.6-1.el8.noarch
python39-pulp-deb-2.20.0-1.el8.noarch
python39-pulp-file-1.11.1-1.el8.noarch
python39-pulp-python-3.7.2-2.el8.noarch
python39-pulp-rpm-3.18.14-1.el8.noarch
rubygem-pulp_ansible_client-0.15.0-1.el8.noarch
rubygem-pulp_certguard_client-1.5.5-1.el8.noarch
rubygem-pulp_container_client-2.14.2-1.el8.noarch
rubygem-pulpcore_client-3.21.2-1.el8.noarch
rubygem-pulp_deb_client-2.20.0-1.el8.noarch
rubygem-pulp_file_client-1.11.2-1.el8.noarch
rubygem-pulp_ostree_client-2.0.0-0.1.a1.el8.noarch
rubygem-pulp_python_client-3.7.3-1.el8.noarch
rubygem-pulp_rpm_client-3.18.7-1.el8.noarch
rubygem-smart_proxy_pulp-3.2.0-3.fm3_3.el8.noarch

**Comment by ggainey** [comment]
Pulp relies on aiohttp  to "do the right thing" at this level. There don't appear to be any knobs to turn on aiohttp.ClientSession for this. I'm not even certain that Pulp **could** notice this specific problem and force a "retry w/ IPv4 ony". One could define the Remote-url to have the IPv4 address instead of the FQDN, but that comes with its own level of unreliability.  In any event, there's only so much Pulp is willing to take on board to deal with Other People's Badly-Configured Servers :)

Just a quick note RE timeouts - Remote does expose the aiohttp.ClientSession parameters `total_timeout`, `connect_timeout`, `sock_connect_timeout`, and `sock_read_timeout` (see https://docs.pulpproject.org/pulpcore/restapi.html#tag/Remotes:-File/operation/remotes_file_file_create , for example). But I don't think shortening the timeout would help in this case, it'll just retry faster, query the same DNS entry, and get back the same IPv6 again, I believe.
