### ISSUE TITLE
Pulpcore prevents the use of keep-alive and may exhaust port numbers in large syncs

### ISSUE THREAD

**Issue by mdellweg** [pulp/pulpcore#4452]
**Version**
Probably all.

**Describe the bug**
Pulp set's force_close on all downloaders and all aiohttp sessions. This prevents any keep-alive functionality and can lead to an exhaustion of tcp ports for large syncs. Some suboptimal network configuration and you end up with servers closing connections, because they believe they are still in time_wait state.

**Steps to reproduce**
Unclear. But maybe a proxy is involved, multiplying the connection creation dilemma.

**Expected behavior**
Pulp should use HTTP/1.1 features when available.

**Additional context**
Creating millions of tcp connections may even be a performance bottleneck.

**Comment by bmbouter** [comment]
Here's a little background on why `force_close` is used. It would be great to remove it, but it could create many other sync issues. Read the history below.

Early in pulp3's history I investigated a content checksum during downloading mismatch bug. It was a difficult one which required tcpdump analysis to determine why the bits we were receiving were different from the checksums being advertised. The root cause determined then (years ago now) was that some webservers although they advertised HTTP 1.1 compliance for TCP session reuse actually didn't handle it properly which caused the bits we received to be incorrect when using session reuse to mismatch. This line was the bugfix at which point all the checksum issues went away. Maybe things have changed since then either in the aiohttp library through uploads, or maybe in upgrades across webservers throughout the world, so perhaps things are different now. Anyways, that's where this came from.

**Comment by bmbouter** [comment]
I'm +1 to try this and I LGTM'd the associated PR.
