### ISSUE TITLE
As a user, I can guard a Distribution with multiple Content Guards with an 'OR' behavior

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#4583]
**Is your feature request related to a problem? Please describe.**
The RH deployment needs to be able to use multiple content guards to guard a Distribution. If any of these content guards authorize it should be allowed, if none of them do, it should be denied.

**Describe the solution you'd like**
It would be really nice to just have them as a list on the Distribution.

**Describe alternatives you've considered**
We could create an 'OR' content guard which then references N content guards as an OR. I don't prefer this solution as it requires more calls to determine how a Distribution is protected.

**Additional context**
Different users need to use different authentication mechanisms, e.g. some want Basic Auth, but others use cert auth.

**Comment by ggainey** [comment]
Observations:
* we could add "list of content-guards" to create-distribution while keeping the existing "add one content-guard"
  * would not break current-API
  * implementation of "just one" becomes a wrapper around "list" call
  * would "imply" "just OR" - if any one CG says "yes", approve, requires ALL to say NO to result in a 403
  * if it becomes desirable to do something more complicated than OR, the REST API becomes...ugly
* we could build a CompositeContentGuard implementation, as mentioned above
  * doesn't change existing API at all
  * isolates complex-decision-making into one place/object
  * figuring out what such a Thing is actually doing, can be/will become Complicated
    * test-combinatorics may get...spicy

My personal preference is for the CompositeContentGuard, FWIW.

**Comment by mdellweg** [comment]
I prefer the composit content guard too. Architecture wise it is nicely contained in a single class.
The only concern i have is that it may produce a lot of additional db queries on every single request to the guarded content.

**Comment by bmbouter** [comment]
The pro/con analysis looks solid to me.

In terms of how we feel about those pro/cons, this kind of gets back to our project values discussion. At the level of code complexity in question here, I value user experience over the code complexity. Adding a `content_guard_list` (or similarly named) would keep our API simple from a usability perspective. With that design, users can answer this question with a single call:

* Is there one or more authorization mechanisms in place on this distribution?
* Why am I getting a 401 error?

**Comment by mdellweg** [comment]
I believe the composit content guard concept is easy to grasp from a users perspective.
Also it allows to reuse the same "set of content guards" in multiple places being configured once. And by the power of RBAC you can even split defining and using these access rules between different personas.
Having both content-guard and content-guard-list on the distribution is imo rendering the api more confusing.

**Comment by ggainey** [comment]
> * Is there one or more authorization mechanisms in place on this distribution?

With the implementation in the associated PR, the answer to that is "Is the content_guard field set on this Distribution". It's true that you need to "notice" that that might be a CCG.

> * Why am I getting a 401 error?

"Why am I denied access" is a hard question to answer right now, but that's because the existing contentguards are inconsistent about how they return "Permission Denied", and generally return minimal data beyond slightly-different ways of saying "No." Only in the logs do current content-guards record information about **why** permission is denied. 

There is a debate in the security-realm around how much info should be returned from a "permission denied" error - should one return enough info that the user can correct their attempt? Or is that leaking info to an attacker, so all you return is "No".  In any event - "how much info should be returned when I deby permission" needs to be answered by the current contentguards, and isn't changed by how we choose to answer this feature request.

I believe that the benefits of not changing the current API and being able to reuse CCGs for multiple Distributions **improves** usability, where the list does not.
