### ISSUE TITLE
Cleanup old publications - general cleanup

### ISSUE THREAD

**Issue by mikch06** [pulp/pulpcore#4817]
**Is your feature request related to a problem? Please describe.**
We do a lot of different new repos and publications - and also delete them after certain time.
Now i see, the publications resist.
Means, in normal handling we have hundreds of publications.
But, we don't know where they do belong to, becuase there is no name tag. 

**Describe the solution you'd like**
May be there is a possibility to remove old publications with no belonging or link to a repository or distribution. 

**Describe alternatives you've considered**
No idea, i just think about an clenaup job.

**Comment by ipanova** [comment]
For automatic cleanup, have you considered using retain_repo_version setting on the repository? With this PR there will be a change in behavior and t will automatically delete only those repo versions that are not distributed( directly or via publication) https://github.com/pulp/pulpcore/pull/4750

**Comment by ipanova** [comment]
If you set `retain_repo_versions`to 1 when creating the repository it will make sure that only 1 repo version will always be in the repo and the rest will be automatically deleted (given that they are not distributed).

Then you just need to trigger orphan clean up that will take care of  orphaned packages.
There is no need to re-create repo, remote, distribution every month.

If you care about and distribute always one and latest repo version then you can simply:

1. create repo with `retain_repo_versions`set to 1. You can also take advantage of `autopublish=True`.
2. create remote, distribution
3. on the distribution instead of publication set the `repository` field

With this setup, if you sync with `mirror` policy you will have:
1. latest repository version automatically published. No need for the manual step to create publication( that's the autopublish option).
2. repository will keep only 1 repo version, because rest will be deleted ( together with publications)
3. Because you synced with mirrored policy you will have only that content locally that is available remotely, namely your repository version will match exactly same content as on the remote source

My assumptions is that your workflows is about rpm repos. Here you can find more docs about sync_policy, retain_repo_versions and autopublish
* https://docs.pulpproject.org/pulp_rpm/workflows/create_sync_publish.html
* https://docs.pulpproject.org/pulp_rpm/restapi.html#tag/Repositories:-Rpm/operation/repositories_rpm_rpm_create
* https://docs.pulpproject.org/pulp_rpm/restapi.html#tag/Repositories:-Rpm/operation/repositories_rpm_rpm_sync
* 
If you're workflow is related to another plugin than you need to check its details because not every plugin supports same options.

**Comment by mikch06** [comment]
Thx a lot, yes we know a lot all the settings. we have a lot of rpm repos and use them with autopublish. 
But i never set a retain_repo_versions. Means i try to update them know and see if orphans will help to clean them up.

**Comment by ipanova** [comment]
Mind that the default retention for orphan clean up is 24h, so whether trigger the orphan clean up later, or decrease the `ORPHAN_PROTECTION_TIME`

I am going to close this issue, because publications are removed with removal of repo version.
Let us know if you still struggle with the optimal worklow and reach out to us via matrix or discourse.

**Comment by ipanova** [comment]
Sweet.

**Comment by mikch06** [comment]
Cool, thx!
