### ISSUE TITLE
Introduce --filter-by option during sync

### ISSUE THREAD

**Issue by swetha65** [pulp/pulpcore#5021]
## Summary

I have a use case where I have one distribution link to be given to multiple users. **All users must use the same link and CANNOT have different links.**
The artifacts required for all the users are put into the same repository and distributed but the users must pull only the artifacts that are required by them. 
Can we have a flag during sync to filter out only certain artifacts? This way, users can avoid syncing all the artifacts into their repositories. 

## Examples

pulp file repository sync --repository REPO --remote REMOTE --mirror --filter-by "$REGEX"
For eg - pulp file repository sync --repository REPO --remote REMOTE --mirror --filter-by "\buserA\b"
This will sync only the artifacts which contain the word "userA" in their relative paths.

**Comment by ggainey** [comment]
OK, the problem here is you want to use Distributions in a way that doesn't match their design/architecture, I'm afraid. Distributions are where content-management is implemented; the general Pulp workflow for 'limiting access to content' would be to have each client have its own repo with a distribution serving it. 

The goal of `sync` is to ask a remote repository "what do you have", and make it accessible inside Pulp. `mirror`, in particular, promises to make **an exact copy** of the Remote - so it makes even less sense to use it, while interfering with the sync process in some way. 

A way for your client-Pulp-instances to achieve something like what you want, would be to do something like:

- central pulp server has All The Files in one repository
- clients sync that repository
- client 'foo' creates its own repository, copies content named *Foo* into that repository, publishes it, creates a distribution and publicizes *that* for *their* clients.

The way Pulp helps users deal with the space-issue is via the `on_demand` policy on Remotes. With on_demand set, your client-Pulp-instances would only end up with the actual content being downloaded, when the systems installing-content-from a given client ask for it.
