### ISSUE TITLE
default domain does not respect REDIRECT_TO_OBJECT_STORAGE

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#5630]
**Version**

3.55

Changing REDIRECT_TO_OBJECT_STORAGE to False does not change the behavior of the default domain.

**Comment by gerrod3** [comment]
Some settings are unique per-domain, REDIRECT_TO_OBJECT_STORAGE is one of them:
https://github.com/pulp/pulpcore/blob/a2ef3bc5a4756f3f6a5c72123c13b0e43131b207/pulpcore/app/models/domain.py#L42-L44
When you want to change these settings you must update the domain. For the default domain that gets its values from the settings file you must update the domain through the migrate command since you can't edit the default domain  through the api:
https://github.com/pulp/pulpcore/blob/a2ef3bc5a4756f3f6a5c72123c13b0e43131b207/pulpcore/app/apps.py#L320-L329
