### ISSUE TITLE
APIs for creating upload and uploading file chunk have same pulp_last_updated timestamps

### ISSUE THREAD

**Issue by xbhouse** [pulp/pulpcore#5751]
We noticed the `pulp_last_updated` timestamps match when creating an upload and uploading a file chunk:

[Create an upload](https://pulpproject.org/pulpcore/restapi/#tag/Uploads/operation/uploads_create):
```
{
    "pulp_created": "2024-08-28T20:11:24.213258Z",
    "pulp_href": "/api/pulp/f54ec6a0/api/v3/uploads/01919a9d-46b5-728a-8ad2-0906c169037a/",
    "pulp_last_updated": "2024-08-28T20:11:24.21327Z",
    "size": 7036
}
```

[Upload a file chunk](https://pulpproject.org/pulpcore/restapi/#tag/Uploads/operation/uploads_update):
```
{
    "pulp_created": "2024-08-28T20:11:24.213258Z",
    "pulp_href": "/api/pulp/f54ec6a0/api/v3/uploads/01919a9d-46b5-728a-8ad2-0906c169037a/",
    "pulp_last_updated": "2024-08-28T20:11:24.21327Z",
    "size": 7036
}
```

I'd expect `pulp_last_updated` to change when uploading new data, but maybe this is intended behavior?

**Comment by mdellweg** [comment]
Interesting. Well adding a chunk to the upload object does not change the upload object in the database, so surely the autodate field will not be updated. And in a way the "upload" being the envelope for all the chunks did indeed not change. You could argue both ways.
Since you cannot actually change an upload, i believe last updated and created will always (almost) coincide.

**Comment by xbhouse** [comment]
ah okay! that makes sense, thanks for clarifying
